doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            id: 'App\Model\ValueObjects\IdType'
            user_email: 'App\Model\User\Entity\EmailType'
            user_id: 'App\Model\User\Entity\IdType'
            product_sku: 'App\Model\Product\Entity\SkuType'
            product_status: 'App\Model\Product\Entity\StatusType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Product/Entity'
                prefix: 'App\Model\Product\Entity'
                alias: Product
            ProductDetail:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Product/Entity'
                prefix: 'App\Model\Product\Entity'
                alias: ProductDetail
            Brand:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Product/Entity'
                prefix: 'App\Model\Product\Entity'
                alias: Brand
            Category:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Category/Entity'
                prefix: 'App\Model\Category\Entity'
                alias: Category