version: '3'
services:
    nginx:
        container_name: nginx-container
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
            - mailer
        ports:
            - "8080:80"
            - "8090:443"
    php-fpm:
        container_name: php-fpm-container
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        depends_on:
            - mysql
            - mailer
        environment:
            XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
            PHP_IDE_CONFIG: "serverName=docker"
            # for macOS IP 10.254.254.254
    node:
        image: node:11.13-alpine
        volumes:
            - ./:/app
        working_dir: /app
        tty: true
    mysql:
        container_name: mysql-container
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=symfony
        restart: always
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - '8081:80'
        volumes:
            - /sessions
    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"

volumes:
    mysql:
    composer: