#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#controllers:
#    resource: '../src/Controller/'
#    type:     annotation

#frontend_index:
#    path: '/{req}'
#    defaults: { _controller: App\Controller\IndexController::index }
#    requirements:
#        req: "^((?!api).)*$"

api_login_check:
    path: /api/login_check

#fos_oauth_server_token:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
#
#fos_oauth_server_authorize:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
